<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Parquet.Net" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketData.Domain\MarketData.Domain.csproj" />
  </ItemGroup>

</Project>
